### ISSUE TITLE
can be overlapped clusters generated  by your code for social network community detection?

### ISSUE THREAD

**Issue by Sandy4321** [seijimaekawa/acMark#2]
great code thanks
1
can be overlapped clusters generated  by your code for social network community detection?
2
what python code you would recommend to try to use it for social network community detection?

https://github.com/dakuang/symnmf
or
https://github.com/seijimaekawa/NAGC

or something else is better?

**Comment by seijimaekawa** [comment]
> great code thanks
> 1
> can be overlapped clusters generated by your code for social network community detection?
> 2
> what python code you would recommend to try to use it for social network community detection?
> 
> https://github.com/dakuang/symnmf
> or
> https://github.com/seijimaekawa/NAGC
> 
> or something else is better?

Very sorry that I could not reply so long. 
As for the 1st question, our generator does not support overlapped clusters. 
Generating overlapped clusters is really challenging and it would be an interesting future direction. 
For the 2nd question, I recommend our clustering method, NAGC, which is NMF-based. 
Also, GCN is recommended, whose python code is publicly open.
